# Database
DATABASE_URL: "mongodb+srv://dowwin_v1_api:GAdIZyP3ObL6YZhP@cluster0.lp5l4.mongodb.net/Dowwin?retryWrites=true&w=majority"

# Slack
SLACK_BOT_TOKEN: "xoxb-1518310205110-1544392027987-rY62XGdCfY9dFtN5sII2OTRm"

# Alpaca
ALPACA_API_SECRET_KEY: '4CtS8LOFcGI0PJsO9wrU3ddBAHGPPNaAfGsom5jH'
ALPACA_API_KEY: 'PKL7HET7GQ96FGE39LFD'

