# Database
DATABASE_URL: "mongodb+srv://trading_agent:Lc2gwI5aUjnVXYoU@cluster0.y7n4w.mongodb.net/Dowwin?retryWrites=true&w=majority"

# Slack
SLACK_BOT_TOKEN: "xoxb-1518310205110-1544392027987-rY62XGdCfY9dFtN5sII2OTRm"

# Alpaca
ALPACA_API_SECRET_KEY: '4CtS8LOFcGI0PJsO9wrU3ddBAHGPPNaAfGsom5jH'
ALPACA_API_KEY: 'PKL7HET7GQ96FGE39LFD'

