# Database
DATABASE_URL: "mongodb+srv://trading_agent:Lc2gwI5aUjnVXYoU@cluster0.y7n4w.mongodb.net/Dowwin?retryWrites=true&w=majority"

# Slack
SLACK_BOT_TOKEN: "xoxb-1518310205110-1544392027987-rY62XGdCfY9dFtN5sII2OTRm"

# Alpaca
ALPACA_API_SECRET_KEY: 'ZuBr5a4VtQSUpOI2fSOerfDWeZN7bAZzTJeDUPrC'
ALPACA_API_KEY: 'PKJMPWBA5B23DPYRZUMK'

