# Trading 
STARTING_FUND: 100000


# Database
DATABASE_URL: "mongodb+srv://dowwin_v1_api:GAdIZyP3ObL6YZhP@cluster0.lp5l4.mongodb.net/Dowwin?retryWrites=true&w=majority"

# Slack
SLACK_BOT_TOKEN: "xoxb-1518310205110-1544392027987-rY62XGdCfY9dFtN5sII2OTRm"

# Alpaca
# Authentication for using Alpaca API.
ALPACA_API_SECRET_KEY: 'ZuBr5a4VtQSUpOI2fSOerfDWeZN7bAZzTJeDUPrC'
ALPACA_API_KEY: 'PKJMPWBA5B23DPYRZUMK'

